export const specificCities = [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Jaipur",
    "Ahmedabad",
    "Pune",
    "Lucknow",
];

export const SkillOptions = [
    "React.js",
    "ReactNative",
    "Node.js",
    "Express",
    "MongoDB",
    "MySQL",
    "HTML",
    "CSS",
    "JavaScript",
    "BootStrap",
    "JQuery",
    "VueJs",
    "Angular",
    "TypeScript",
    "Python",
    "Django",
    "Flask",
    "Laravel",
    "Ruby",
    "PHP",
    "Java",
    "C#",
    "Swift",
    "Kotlin",
    "Objective-c",
    "GoLang",
    "Spring Boot",
    "Hibernate",
    "Spring Data JPA",
    "Hibernate Search",
    "Elasticsearch",
    "Solr",
    "Apache Kafka",
    "Zookeeper",
    "Hadoop",
    "Spark",
    "Flink",
    "Pig",
    "HBase",
    "Redis",
    "Memcache",
    "AWS",
    "GCP",
  ];

  export const positionOptions = [
    "Software Engineer",
    "Data Scientist",
    "Product Manager",
    "UX Designer",
    "UI/UX Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "DevOps",
    "Project Manager",
    "QA Tester",
    "Sales & Marketing",
    "Digital Marketer",
    "SEM Specialist",
    "Content Writer",
    "Copywriter",
    "Graphic Designer",
    "Illustrator",
    "Photographer",
    "Videographer",
    "Web Analyst",
    "Database Administrator",
    "Network Administrator",
    "Security Officer",
    "Cybersecurity Consultant",
    "IT Project Manager",
    "Cloud Architect",
    "AI/ML Engineer",
    "Chief Technology Officer",
    "CTO",
];

export const experienceOptions = [
    "Less than 1 year",
    "1-2 years",
    "3-5 years",
    "6-10 years",
    "10+ years",
];